### ISSUE TITLE
Back-end: Create api to register the user

### ISSUE THREAD

**Issue by BBaggines** [airavata-courses/Spark#11]

**Comment by aralshi** [comment]
User Object:
{
    "first_name":"Ankita",
    "last_name":"Alshi",
    "email":"aralshi@iu.edu",
    "password":"********",
    "dob":"01/01/1992",
    "gender":"Female",
    "country":"India"
  }

**Comment by aralshi** [comment]
API used to register new user into the system. UI will send user details to this API in JSON format. All fields are required. 
API path : /api/register
