### ISSUE TITLE
Peer review 1 - Comments on Wiki

### ISSUE THREAD

**Issue by psethu** [airavata-courses/Spark#34]
Overall, the steps are nicely concise. Wiki is divided into sections which enables reader to quickly understand the architecture of the entire application. The setup directions are also very step by step.

There are just couple points for further enhancement:
1. Directions are available for Linux, Mac, Windows. Instructions are comprehensive by addressing the major platforms. For Windows, it feels there is slightly less instructions. Can add additional such as discussing PATH system variable.

2. A generic note on reasoning for selected technology choices. This is just providing more information on the project but can help specify further motivation comprehensively. Some explanation areas:
- why choosing a SQL database such as mySQL over NoSQL database such as MongoDB
- why choosing Node.js environment for administering the login service

**Comment by BBaggines** [comment]
> Overall, the steps are nicely concise. Wiki is divided into sections which enables reader to quickly understand the architecture of the entire application. The setup directions are also very step by step.
> 
> There are just couple points for further enhancement:
> 
> 1. Directions are available for Linux, Mac, Windows. Instructions are comprehensive by addressing the major platforms. For Windows, it feels there is slightly less instructions. Can add additional such as discussing PATH system variable.
> 2. A generic note on reasoning for selected technology choices. This is just providing more information on the project but can help specify further motivation comprehensively. Some explanation areas:
> 
> * why choosing a SQL database such as mySQL over NoSQL database such as MongoDB
> * why choosing Node.js environment for administering the login service

Hey,
Thanks for the suggestions. We have added more Windows-specific steps which will help windows user better([4a8d2e](https://github.com/airavata-courses/Spark/wiki/Assignment-1/4a8d2e269e7dfd7dfb0b082056c9c1d3bf3ba8e8)).  
While the questions raised are good/valid questions, we did not find it necessary to include them in the current wiki which included the steps for installation. We will try to include a separate document which can talk more about our choices of different technologies.
