### ISSUE TITLE
Peer review (Milestone 1)

### ISSUE THREAD

**Issue by arbansal** [airavata-courses/Spark#35]
The following (minor) issues were noticed after going through the wiki and executing the steps:
1. If another process on my machine is already utilizing port 8080, there should be a mechanism in given service to either use a different port or kill existing process after taking user's permission.
2. There is a scope of improvement in the wiki wherein the steps to install Java and using maven can be illustrated better.

**Comment by BBaggines** [comment]
Hey,
Thank you for the above suggestions.
1. For the first issue, we have not included the suggestion in this milestone. However, we would keep it in mind for the next milestone. 
2. We have included the link for the installation of Java in the wiki. We have also included the maven install and run steps which can be used to run through the prompt ([bfc2d0e](https://github.com/airavata-courses/Spark/wiki/Assignment-1/bfc2d0e46f31d487146272098b11838213fcefd4)).
