### ISSUE TITLE
Peer Review - 1st Milestone

### ISSUE THREAD

**Issue by vanessapinto257** [airavata-courses/Spark#37]
When I try to run `Login` micro service, I get the following error:

> Error: listen EADDRINUSE: address already in use :::8080
>     at Server.setupListenHandle [as _listen2] (net.js:1277:14)
>     at listenInCluster (net.js:1325:12)
>     at Server.listen (net.js:1412:7)
>     at Object.<anonymous> (/Users/vanessa/Documents/Courses/Science Gateway Architectures/spark/Spark-login/findyournextmovie/server.js:4:24)
>     at Module._compile (internal/modules/cjs/loader.js:689:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
>     at Module.load (internal/modules/cjs/loader.js:599:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:530:3)
>     at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
> Emitted 'error' event at:
>     at emitErrorNT (net.js:1304:8)
>     at process._tickCallback (internal/process/next_tick.js:63:19)
>     at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
>     at startup (internal/bootstrap/node.js:283:19)
>     at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
  Also, I believe this issue does not let me run the other services as well

`

**Comment by aralshi** [comment]
can you please let me know command you used? you are using develop-login_service branch right?

**Comment by vanessapinto257** [comment]
Yes, I'm using the `develop-login_service` branch and this happens when I run the `npm start` command to run the microservice.

**Comment by vanessapinto257** [comment]
Thank you for getting on a call with me and helping me resolve the issue.

The following is my review:
1. The UI looks really good.
2. The user can find any movie possible on your website along with movie summary, rating and cast details which is amazing.
3. The user can also save their own rating for any movie.


Some issues that I encountered were:
1. It wouldn't let me login with an email ID I had just registered prior. When I checked the terminal it showed that the email was too long for the database but it is a valid email ID and when I had used the same ID to create a new account there was no issue.
2. Get suggestions did not work for me.
3. On the sign in page , there is a date field but there is no mention of what the date is supposed to be of.

Overall the website looks great and works great!

**Comment by aralshi** [comment]
1. Can you please tell the email id, I will check.
2. Suggestions wont work if you are not logged in. 
3. Thats for birthdate we will change it to mention the same.

Thanks!

**Comment by vanessapinto257** [comment]
The email id I used was vanessapinto257@gmail.com.
Also, I had tried suggestions as a logged in user and it still hadn't worked

**Comment by kulsv** [comment]
Hey Vanessa,

can you please run the following queries for mysql and see if this long email id is working for you?

DROP TABLE users;

CREATE TABLE users (user_id varchar(36), first_name VARCHAR(20), last_name VARCHAR(20), email VARCHAR(50), password VARCHAR(100), dob DATE, gender CHAR(1), country VARCHAR(20), created DATE, modified DATE);

**Comment by vanessapinto257** [comment]
Yeah everything is working great now!  Thank you!
