### ISSUE TITLE
Assignment 1 feedback

### ISSUE THREAD

**Issue by raghu2094** [airavata-courses/Spark#38]
Hi Team,

I have completed reviewing your assignment. I was able to start and run all the microservices successfully without any issues. Quite impressed with the work done so far. UI looks neat with seamless integration of all the services. 
Architecture diagram and napkin diagram clearly describes the idea and purpose of the application.
 Working of the services and steps for installation have been well-documented. Had no issues in cloning and starting the project. 
  
Curious about the API being used. Is there any limit on the number of fetches or any other restriction for that matter and if so how are you handling it? 
Are you planning on implementing any new features for the next assignment ?
In my opinion, showing the movies already rated by the user on the user's homepage can be a good enhancement. This would avoid user having to navigate to the movie page every time to check if the movie has been rated or not.

Overall great job and keep up the good work!

Regards,
Raghottam

**Comment by BBaggines** [comment]
Hey Raghottam,
Thanks for the comments and suggestions.
Answering the questions asked, there is a limit on the maximum number of fetches from TMDb API which is 1000 for free accounts. If there is a need for more number of fetches from the API, a paid plan can be used which will increase the number of possible hits on the API.
For the suggestion of distinguishing the watched movies in the users' homepage, we have created an issue for the same as an enhancement. 

Thanks,
Spark
