### ISSUE TITLE
Error in UI [develop-react_UI]

### ISSUE THREAD

**Issue by alakhsingh** [airavata-courses/Spark#64]
Hi,
When I click the search button with an empty string I receive an error 'TypeError: Cannot read property 'map' of undefined'
Screenshots attached below
<img width="1120" alt="screenshot 2019-03-03 at 12 09 00 pm" src="https://user-images.githubusercontent.com/20154848/53698629-78648180-3dad-11e9-9e78-7cd023f36ab3.png">

**Comment by aralshi** [comment]
Hi @alakhsingh,

Shweta just pushed a small fix to remove this error. Please let us know if we can close this issue.

**Comment by kulsv** [comment]
Hi Alakh,

Thank you for bringing this to our notice. We have fixed this issue. Could you please test this again?
Thanks,
Shweta

**Comment by alakhsingh** [comment]
Hi,
Looks perfect.
Closing the issue.
