### ISSUE TITLE
Error in fetching some URL (Peer review milestone 2)

### ISSUE THREAD

**Issue by mkhambat** [airavata-courses/Spark#65]
Hi,
I on the landing page, I am getting an error which says error in fetching some URL.

**Comment by BBaggines** [comment]
Hey Murtaza,
Thanks for bringing that to our notice. One of the services was down and we are unclear on the reason as of now. We have started the service again. 
Please try again and let us know if you find any issues.

Thanks and regards,
Shradha

**Comment by mkhambat** [comment]
Issue fixed
