### ISSUE TITLE
Error in get suggestions [develop-suggestion_service]

### ISSUE THREAD

**Issue by alakhsingh** [airavata-courses/Spark#67]
Hi,
When clicked `get suggestions` button, It doesn't load the next page. I get an error. I think this happened after doing CI/CD build testing although all the builds have passed.
 Attaching the screenshots below
<img width="1168" alt="screenshot 2019-03-03 at 12 07 33 pm" src="https://user-images.githubusercontent.com/20154848/53698662-e27d2680-3dad-11e9-9dbe-a4a35d9394cd.png">

**Comment by aralshi** [comment]
Hi @alakhsingh 

I think the suggestion service was down for some reason. can you check once again?

**Comment by alakhsingh** [comment]
It works now,
closing the issue.
