### ISSUE TITLE
404 Error on console when searching for a movie

### ISSUE THREAD

**Issue by mkhambat** [airavata-courses/Spark#68]

**Comment by mkhambat** [comment]
Even though I am getting a 404 error on console while searching for a movie, the correct search results do show up

**Comment by BBaggines** [comment]
Hey Murtaza,
I am a bit unclear on this issue. Can you provide a screenshot of the error on the console so that we can may be debug it ?

Thanks and regards,
Shradha

**Comment by mkhambat** [comment]
Hey, 
The issue was also brought up by Alakh, also now it has been fixed!
