### ISSUE TITLE
 I always get `Sorry! Some error in fetching the url` error 

### ISSUE THREAD

**Issue by alakhsingh** [airavata-courses/Spark#69]
Hi,
For some reason, I am always getting this error although I don't see any errors in the UI, all the data loads fine.
 Attaching the screenshots below
<img width="681" alt="screenshot 2019-03-03 at 12 00 14 pm" src="https://user-images.githubusercontent.com/20154848/53698691-325bed80-3dae-11e9-9c2b-974d69fcd41a.png">

**Comment by aralshi** [comment]
Hi @alakhsingh,

Should I close this as you said that its working for you?

**Comment by alakhsingh** [comment]
Hi,
Closing the issue.
