### ISSUE TITLE
Peer review 2

### ISSUE THREAD

**Issue by alakhsingh** [airavata-courses/Spark#70]
Hi team,

Jenkins CI/CD test
Your application looks perfect. I have added dummy commits and all deploys are successful.
Your UI looks neat.

I have opened a few issues for minor bugs found.  I have added the issue numbers below. Please check them out for more details.
#64, #67, #69

Suggestions
- For a few movies, there isn't any proper image or in a few images, the head of the actor/actress is cut off. It would be great if you could scale the images relatively.
In the end when considering the big picture, one of the best projects I have seen until now.

**Comment by kulsv** [comment]
Hi Alakh,

We have resolved the issue #64 
Please check out the other comments on the issues and please close them if you find them to be working.

Also, Thanks a lot for the suggestion. We're right now working on some more functionalities but we'd definitely like to give your suggestion a try.

Thank you, really appreciate it.
-
Shweta
