### ISSUE TITLE
Error while Searching  

### ISSUE THREAD

**Issue by prathameshd** [airavata-courses/Spark#71]
When I search for a movie i am getting an error 'Sorry! Some error occurred.'

**Comment by kulsv** [comment]
Hi Prathamesh,

Thank you for letting us know.
Could you please tell me if you entered any string to be searched or were trying with empty string?

Shweta

**Comment by prathameshd** [comment]
I tried searching with both-a query and empty string which gave me an error.

**Comment by kulsv** [comment]
Could you please test it again? We've fixed the empty string issue.

**Comment by prathameshd** [comment]
Yes I checked, its working now. Closing this issue.
