### ISSUE TITLE
Peer Review 2

### ISSUE THREAD

**Issue by prathameshd** [airavata-courses/Spark#73]
Hi Team,
The app looks good. Tested continuous deployment on Jenkins via build commits and all build were succcessful. I faced the following issues #69 #66 #71 #72  while running the app. 
I have a few suggestions:
• For the git structure, all services can be combined under one single branch for this milestone.
• Each service had to be built separately for Jenkins. Ideally, a single commit should trigger builds of all services.

**Comment by BBaggines** [comment]
Hey Prathamesh,
I will individually reply to all the issues created. For the mentioned suggestion, we did not want to rebuild all the services in case one of the service is updated with new code. This is the reason why we have avoided a single commit trigger for all. 
Also, during the first lecture, it was mentioned as a suggestion by the professor to maintain a separate branch for all the services (the develop branches). We have tried to stick to that.

Thanks and regards,
Shradha

**Comment by prathameshd** [comment]
All services work perfectly now. Good work!
