### ISSUE TITLE
Review for Assignment 2

### ISSUE THREAD

**Issue by nawazkh** [airavata-courses/Spark#81]
Hey Team,
I was about to start the review for assignment2.
Please share your Jenkins credentials with me on Slack.

**Comment by nawazkh** [comment]
Hey team, 
I was reviewing your system. There is no order specified in the project to run the jobs, Can I run it in any order?

**Comment by nawazkh** [comment]
Hey Team, I am not able to deploy login-build-test-deploy pipeline. Please let me know how I can proceed here.

**Comment by aralshi** [comment]
Hi @nawazkh,
Thanks for reaching out. I have fixed the error in Jenkins file of login service. Please proceed as given below:
Deploy service:
1. login
2. search
3. rating
4. suggestion
5. react UI

Access the website at : http://149.165.169.128:30002

I will update the wiki to reflect the same.

**Comment by nawazkh** [comment]
Hey Team, I am sorry I forgot to share my feedback, so here it goes.
There were few things missing at the time of grading of assignment 2, I have listed them below:
1. I did not find any test cases in your modules, please do write test cases for your modules so that continuous integration shows right results.
2. The services were being built on the same instance where they were being deployed. IMO, there should be one dev environment used to build a system and deploy it to production servers. Please do implement that.
3. Documentation pertaining to Assignment 2 was not very detailed. Please mention the tasks achieved using zookeeper and the steps zookeeper does to support your system.
4. We are also looking for functionality improvement, so if there was any functionality improved over as the part of sprints, do include it in your wiki.
 
However, I really like the project concept and the work put behind it. 
Keep up the good work!

**Comment by aralshi** [comment]
Hi @nawazkh 

Thanks for your feedback. We have written test cases for 2 java spring micro services and python micro service. We are writing test cases for node js service. We have separate server for Jenkins and we are using that instance to build the system. Once the service is build successfully we are deploying it to production servers. We will try to keep the documentation in depth going forward.

Thanks,
Ankita Alshi
