### ISSUE TITLE
Peer Review Assignment 3

### ISSUE THREAD

**Issue by shubham1812** [airavata-courses/Spark#89]
Hi Team, 
I tried testing your website but looks like it is not working right now. Also, can you please send me your Jenkins credentials so that I can check the Ci/Cd pipeline.
Suggestion: You can add the error percentage during load testing when you increase the number of requests. This way the reader have a better understanding and can visualize in a better way

**Comment by BBaggines** [comment]
Hey Shubham,
Thank you for going through the project. The app seems to be working on our end. The access link is : http://149.165.169.128:30002/.
If you are still unable to get it working by clicking on the link, can you describe the error or the screenshot so that we can debug it ?
Also, the screenshots included in the wiki page for assignment 3 contains the error rate given by Jmeter and a comparison of the same when the number of replicas is increased for 3000 requests.

**Comment by BBaggines** [comment]
Also, Can you share your email id so I can share the Jenkins credentials?

**Comment by shubham1812** [comment]
Hi @BBaggines ,
Please email me the credentials at sgodshal@iu.edu

**Comment by shubham1812** [comment]
Also, 
Please update your wiki to provide links of the website, services and jenkins server

**Comment by BBaggines** [comment]
Hey Shubham,
Thanks for pointing that out. I have updated the wiki page of assignment 3 with links. 
I have also mailed you the jenkins credentials.
Let us know if you need anything else. 

Thank you,
Shradha

**Comment by shubham1812** [comment]
Hi Team,
The website works fine. The services are deploying properly on Jenkins. You have achieved Ci/Cd part. Please add more about your load testing by JMeter in your wiki. What are the errors you are getting in the logs.
 Minor frontend suggestions: 
1. Couldn't find user profile page as mentioned in the architecture diagram. 
2. After clicking get suggestions, the website does not return back to the home page.
3. Confirm password field in the sign-up form is not of type password.

**Comment by kulsv** [comment]
Hi Shubham,
Thank you for all the suggestions.
We have updated the Wiki with more screenshots and you can see the error rate and the throughput in them.
The issue for confirm password not being of type password is fixed. You can test it now.
We are targeting the user's profile page for the next milestone as one more reviewer suggested a few things for the page.
We are working on not being able to return to home page after clicking the suggestion button. We have raised a bug for this.

Thanks,
Shweta
