### ISSUE TITLE
Peer review assignment 3

### ISSUE THREAD

**Issue by rojaraman** [airavata-courses/Spark#92]
Please provide Jenkin credentials.
Do you have k8 dashboard installed? If not please guide me on how to monitor k8 nodes.

Regards,
Roja Raman

**Comment by kulsv** [comment]
Hi Roja,
We do not have the Kubernetes dashboard installed. You can share your ssh key and we will guide you on accessing the Kubernetes master.

**Comment by rojaraman** [comment]
@kulsv I sent it to you via email. Please check and confirm.

**Comment by kulsv** [comment]
Hi Roja,
I have added your public key to the Kubernetes master.
Please follow these commands to test Kubernetes:

1. ssh into kubernetes master: user-ubuntu, ip-149.165.169.128
2. Open two terminal windows simultaneously
3. sudo kubectl get pods - this command will list down all the pods running with the pod names.
4. delete any of the pods from another window -  sudo kubectl delete pods POD_NAME
5. Observe the changes in the first window where "sudo kubectl get pods" is already running.

Please let me know if you face any issues.

-
Shweta

**Comment by rojaraman** [comment]
Hi Team,

UI looks really good. The functionality is working properly. I see that k8 has been set up correctly with minimum downtime. 
I wasn't able to login to Jenkins, as I couldn't find credentials in wiki.

Wiki for Milestone 2 can be more elaborated and you can explain about the implementation a  little more.

Overall, the project looks good.

Thanks,
Roja Raman
